#+title: Undergraduate Projects
#+author: Mayer Goldberg
#+email: gmayer@little-lisper.org
#+options: creator:nil, author:nil
#+keywords: Mayer Goldberg, BGU, Ben-Gurion University, CS, computer science, computer science department, undergraduate software projects, programming

My main requirements from people who do projects with me are
- A weekly report by email (could be two lines long), telling me what
  they have done during the past week, and what they expect to
  accomplish the following week. I don't care if there is no progress
  on a specific week (e.g., during a holiday or exam week, etc), I
  appreciate the fact that you have other responsibilities, and may
  also have a life, and I will not rush you. But I do insist on
  receiving weekly emails, so that I know the status of the
  project. Here is an example of a perfect report: 
  =Hello: I have done absolutely nothing last week, and I expect to do 
  absolutely nothing next week. Have a nice day!=
- A love of programming. If you occasionally [or more!] write programs
  that are not part of a homework assignment or course project, then
  you qualify.
- Independence, creativity & pro-activeness. If you don't know
  something, that's fine -- there are many things that I don't know. I
  do expect you to realize what you don't know, and actively search
  for answers. If you are unable to find answers, then I expect you to
  notify me immediately, so that we can pursue the answers together.

If you wish to participate in any of these projects, [[mailme][please contact me
by email]].

* Open Projects

** 
