#+title: My Journey with Arabic
#+author: Mayer Goldberg ({{{rtl(מֵאִיר גּוֹלְדְּבֵּרְג)}}})
#+email: gmayer@little-lisper.org
#+options: creator:nil, toc:1
#+options: h:2
#+keywords: Mayer Goldberg, Department of Computer Science, Ben-Gurion University, learning languages, arabic

* Colloquial Levantine Arabic ({{{rtl(ערבית מדוברת של המזרח הקרוב (סוריה הגדולה))}}}, {{{rtl(عامية شامي)}}})

Colloquial Levantine Arabic is a collection of closely-related dialects in use in what used to be called /the Greater Syria/, or Sham {{{rtl(شام)}}}. This area includes Lebanon, Syria, Jordan, Israel, the West Bank, Gaza Strip. Historically, it also includes Iraq, although Colloquial Iraqi is a very different dialect, strongly influenced by Persian and Turkish. While I'm picking up some phonetics, and vocabulary from other dialects, the Levantine dialect is currently my main focus when learning Colloquial Arabic.

** Timeline
*** <2023-09-21 Thu> 

My cardfile now stands at 4261 cards. I've added some 230+ cards since the start of the month. This is actually kind of disappointing. I was hoping for more like 1000+ cards, but that didn't happen. I need to step up the pace befor e the semester commences.

Learned to type the short vowels ({{{rtl(حَرَكات)}}}) on the standard Arabic keyboard

I've created my own customized Arabic keyboard input-method for GNU Emacs. I love my input-method because it is based on the standard QWERTY-layout, is very logical, and I can use it to type all sorts of weird stuff, including photetic extensions to Arabic ({{{rtl(پ، ڤ، گ)}}}) that are unavailable on standard Arabic keyboards, but that are necessary for loanwords and dialects. However, my input-method is only available from within GNU Emacs, so in effect, I am typing on *two* Arabic keyboards: The relatively standard one that comes with my linux computers and Android cellular phones, and the input-method I created for Emacs. If I'm ever going to type really quickly in Arabic, I'm going to have to abandon my beloved layout and focus on the standard layout, possibly with some special extensions for Emacs...

I've come to realize that I'm mispronouncing words, confusing the {{{rtl(ح، خ)}}}, {{{rtl(ت، ط)}}}, which are conflated in Hebrew, and {{{rtl(ذ، ظ)}}}, which are not present in Hebrew, as well as dropping long vowels. This is as dangerous a prospect in Arabic as are dropping tone marks in Chinese or Vietnamese. There's a big difference between {{{rtl(حارة)}}} (/neighbourhood/), {{{rtl(خرا)}}} (/shit/), although in some neighbourhoods people are less inclined to pick up after their dogs... And then there is {{{rtl(حارّة)}}} (which is the feminine adjective /spicy hot/). To remedy this problem, I'm writing out the cards for each lesson. This takes longer, and means I'm not studying as many cards, but on the other hand, studying seems to be more effective.

* Modern Standard Arabic (/in planning/)
