#+title: {{{hebrew(לימוד ערבית)}}}
#+author: Mayer Goldberg ({{{hebrew(מֵאִיר גּוֹלְדְּבֵּרְג)}}})
#+email: gmayer@little-lisper.org
#+options: creator:nil, toc:1
#+options: h:2
#+keywords: Mayer Goldberg, Department of Computer Science, Ben-Gurion University, learning languages, arabic
#+html_head: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=David+Libre">
#+html_head: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic">
#+html_head: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Aref+Ruqaa">
#+html_head: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Old+Standard+TT">
#+html_head: <link rel="stylesheet" type="text/css" href="https://mayer-goldberg.github.io/website/hebrew-support/gmayer-org-mode-web.css" />

#+begin_export html
<script src="https://mayer-goldberg.github.io/website/hebrew-support/gmayer-org-mode-web.js"></script>
#+end_export

* משאבים
** ספרים
** מלונים מקוונים
- [[https://milon.madrasafree.com/][המלון המקוון של *מדרסה* לערבית מדוברת]]. המלון פותח, מומש, ותוחזק על ידי [[https://rothfarb.info/][*רונן רוטפרב*]]. ברבות השנים, רונן העביר את הפרוייקט [[https://madrasafree.com/][לבית הספר *מדרסה* לערבית]], ואלו מתחזקים אותו כעת.

** תרגומים אינטרלינאריים
* ערבית מדוברת בניב של המזרח הקרוב (ניב שָׁאמִי, {{{arabic(عامية شامي)}}})

ערבית מדוברת של המזרח הקרוב היא אוסף של להגים המדוברים באיזור שהיסטורית נקרא בשם *סוריה הגדולה*, או שָׁאם ({{{arabic(شام)}}}). האיזור כולל את לבנון, סוריה, ירדן, ישראל, הגדה המערבית, ורצועת עזה. מבחינה היסטורית, *סוריה הגדולה* כוללת גם את עיראק, אבל ערבית מדוברת עיראקית שונה מאד משאר הלהגים של *סוריה הגדולה*, וכולל השפעות רבות מפרסית ותורכית, ולכן מקובל שלא לכלול אותו בלהגים של *סוריה הגדולה*, אלא להתייחס אליו כלהג נפרד.

** Timeline
*** <2023-09-21 Thu> 

My cardfile now stands at 4261 cards. I've added some 230+ cards since the start of the month. This is actually kind of disappointing. I was hoping for more like 1000+ cards, but that didn't happen. I need to step up the pace befor e the semester commences.

Learned to type the short vowels ({{{arabic(حَرَكات)}}}) on the standard Arabic keyboard

I've created my own customized Arabic keyboard input-method for GNU Emacs. I love my input-method because it is based on the standard QWERTY-layout, is very logical, and I can use it to type all sorts of weird stuff, including photetic extensions to Arabic ({{{arabic(پ، ڤ، گ)}}}) that are unavailable on standard Arabic keyboards, but that are necessary for loanwords and dialects. However, my input-method is only available from within GNU Emacs, so in effect, I am typing on *two* Arabic keyboards: The relatively standard one that comes with my linux computers and Android cellular phones, and the input-method I created for Emacs. If I'm ever going to type really quickly in Arabic, I'm going to have to abandon my beloved layout and focus on the standard layout, possibly with some special extensions for Emacs...

I've come to realize that I'm mispronouncing words, confusing the {{{arabic(ح، خ)}}}, and {{{arabic(ت، ط)}}}, which are conflated in Hebrew, and {{{arabic(ذ، ظ)}}}, which are not present in Hebrew, as well as dropping long vowels. This is as dangerous a prospect in Arabic as are dropping tone marks in Chinese or Vietnamese. There's a big difference between {{{arabic(حارة)}}} (/neighbourhood/), {{{arabic(خرا)}}} (/shit/), although in some neighbourhoods people are less inclined to pick up after their dogs... And then there is {{{arabic(حارّة)}}} (which is the feminine adjective /spicy hot/). To remedy this problem, I'm writing out the cards for each lesson. This takes longer, and means I'm not studying as many cards, but on the other hand, studying seems to be more effective.

* Modern Standard Arabic (/in planning/)
