#+title: A disclaimer concerning links to book vendors on this site
#+author: Mayer Goldberg
#+email: gmayer@little-lisper.org
#+options: creator:nil

When I link my website to book pages on some vendors' sites, I do this to help those interested in the given book to
- get copies quickly
- browse pages, read reviews, see related books fromt he vendor's website, etc
- be able to recognize the book at the library, from its cover
What I am not doing is 
- endorsing/promoting the book
- endorsing/promoting the author
- endorsing/promoting the vendor
- making money from promoting either the book or the vendor
When I wish to endorse a book, I do so specifically, stating /why/ I think the book is valuable, and /for what/. Linking to a book is not an endorsment, but an acknowledgement that the book is commonly-used standard text on a subject. While I try to give useful lists of books for reference, you must use your own common sense and good judgement: If you try to buy even the most commonly used texts in an area, you are likely to go broke and run out of shelf space.

Most of my links to books are to [[http://www.amazon.com/][Amazon]]. I do this because
- they have pages for lots of books, including some books that are no longer in print
- they offer previewing of selected pages
- they offer customer reviews
- it is more convenient for me to link to a single vendor, when possible, than to look for a book all over the web
I don't particularly like Amazon these days. In the past, I used to shop there more often. These days I try to shop elsewhere. I am not making any money by linking to Amazon, nor do I consider this venue appropriate for my website. 
